/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as CalendarRouteImport } from './routes/calendar'
import { Route as IndexRouteImport } from './routes/index'
import { Route as SalesNewRouteImport } from './routes/sales/new'
import { Route as InvoicesReviewRouteImport } from './routes/invoices/review'
import { Route as InvoicesNewRouteImport } from './routes/invoices/new'
import { Route as AnalyticsMonthlyRouteImport } from './routes/analytics/monthly'
import { Route as AnalyticsCalendarRouteImport } from './routes/analytics/calendar'
import { Route as InvoicesReviewJobIdRouteImport } from './routes/invoices/review/$jobId'

const CalendarRoute = CalendarRouteImport.update({
  id: '/calendar',
  path: '/calendar',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const SalesNewRoute = SalesNewRouteImport.update({
  id: '/sales/new',
  path: '/sales/new',
  getParentRoute: () => rootRouteImport,
} as any)
const InvoicesReviewRoute = InvoicesReviewRouteImport.update({
  id: '/invoices/review',
  path: '/invoices/review',
  getParentRoute: () => rootRouteImport,
} as any)
const InvoicesNewRoute = InvoicesNewRouteImport.update({
  id: '/invoices/new',
  path: '/invoices/new',
  getParentRoute: () => rootRouteImport,
} as any)
const AnalyticsMonthlyRoute = AnalyticsMonthlyRouteImport.update({
  id: '/analytics/monthly',
  path: '/analytics/monthly',
  getParentRoute: () => rootRouteImport,
} as any)
const AnalyticsCalendarRoute = AnalyticsCalendarRouteImport.update({
  id: '/analytics/calendar',
  path: '/analytics/calendar',
  getParentRoute: () => rootRouteImport,
} as any)
const InvoicesReviewJobIdRoute = InvoicesReviewJobIdRouteImport.update({
  id: '/$jobId',
  path: '/$jobId',
  getParentRoute: () => InvoicesReviewRoute,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/calendar': typeof CalendarRoute
  '/analytics/calendar': typeof AnalyticsCalendarRoute
  '/analytics/monthly': typeof AnalyticsMonthlyRoute
  '/invoices/new': typeof InvoicesNewRoute
  '/invoices/review': typeof InvoicesReviewRouteWithChildren
  '/sales/new': typeof SalesNewRoute
  '/invoices/review/$jobId': typeof InvoicesReviewJobIdRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/calendar': typeof CalendarRoute
  '/analytics/calendar': typeof AnalyticsCalendarRoute
  '/analytics/monthly': typeof AnalyticsMonthlyRoute
  '/invoices/new': typeof InvoicesNewRoute
  '/invoices/review': typeof InvoicesReviewRouteWithChildren
  '/sales/new': typeof SalesNewRoute
  '/invoices/review/$jobId': typeof InvoicesReviewJobIdRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/calendar': typeof CalendarRoute
  '/analytics/calendar': typeof AnalyticsCalendarRoute
  '/analytics/monthly': typeof AnalyticsMonthlyRoute
  '/invoices/new': typeof InvoicesNewRoute
  '/invoices/review': typeof InvoicesReviewRouteWithChildren
  '/sales/new': typeof SalesNewRoute
  '/invoices/review/$jobId': typeof InvoicesReviewJobIdRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/calendar'
    | '/analytics/calendar'
    | '/analytics/monthly'
    | '/invoices/new'
    | '/invoices/review'
    | '/sales/new'
    | '/invoices/review/$jobId'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/calendar'
    | '/analytics/calendar'
    | '/analytics/monthly'
    | '/invoices/new'
    | '/invoices/review'
    | '/sales/new'
    | '/invoices/review/$jobId'
  id:
    | '__root__'
    | '/'
    | '/calendar'
    | '/analytics/calendar'
    | '/analytics/monthly'
    | '/invoices/new'
    | '/invoices/review'
    | '/sales/new'
    | '/invoices/review/$jobId'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  CalendarRoute: typeof CalendarRoute
  AnalyticsCalendarRoute: typeof AnalyticsCalendarRoute
  AnalyticsMonthlyRoute: typeof AnalyticsMonthlyRoute
  InvoicesNewRoute: typeof InvoicesNewRoute
  InvoicesReviewRoute: typeof InvoicesReviewRouteWithChildren
  SalesNewRoute: typeof SalesNewRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/calendar': {
      id: '/calendar'
      path: '/calendar'
      fullPath: '/calendar'
      preLoaderRoute: typeof CalendarRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/sales/new': {
      id: '/sales/new'
      path: '/sales/new'
      fullPath: '/sales/new'
      preLoaderRoute: typeof SalesNewRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/invoices/review': {
      id: '/invoices/review'
      path: '/invoices/review'
      fullPath: '/invoices/review'
      preLoaderRoute: typeof InvoicesReviewRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/invoices/new': {
      id: '/invoices/new'
      path: '/invoices/new'
      fullPath: '/invoices/new'
      preLoaderRoute: typeof InvoicesNewRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/analytics/monthly': {
      id: '/analytics/monthly'
      path: '/analytics/monthly'
      fullPath: '/analytics/monthly'
      preLoaderRoute: typeof AnalyticsMonthlyRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/analytics/calendar': {
      id: '/analytics/calendar'
      path: '/analytics/calendar'
      fullPath: '/analytics/calendar'
      preLoaderRoute: typeof AnalyticsCalendarRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/invoices/review/$jobId': {
      id: '/invoices/review/$jobId'
      path: '/$jobId'
      fullPath: '/invoices/review/$jobId'
      preLoaderRoute: typeof InvoicesReviewJobIdRouteImport
      parentRoute: typeof InvoicesReviewRoute
    }
  }
}

interface InvoicesReviewRouteChildren {
  InvoicesReviewJobIdRoute: typeof InvoicesReviewJobIdRoute
}

const InvoicesReviewRouteChildren: InvoicesReviewRouteChildren = {
  InvoicesReviewJobIdRoute: InvoicesReviewJobIdRoute,
}

const InvoicesReviewRouteWithChildren = InvoicesReviewRoute._addFileChildren(
  InvoicesReviewRouteChildren,
)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  CalendarRoute: CalendarRoute,
  AnalyticsCalendarRoute: AnalyticsCalendarRoute,
  AnalyticsMonthlyRoute: AnalyticsMonthlyRoute,
  InvoicesNewRoute: InvoicesNewRoute,
  InvoicesReviewRoute: InvoicesReviewRouteWithChildren,
  SalesNewRoute: SalesNewRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { createStart } from '@tanstack/react-start'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
  }
}
